<?php 
$config = Mage::getStoreConfig('payment/paybutton');
$arrCart = $this->getCartArray();

?>

<?php if(isset($this->config['view_type']) && $this->config['view_type'] == 'block'): ?>
<div class="module pay-module taply-block" data-type="cart" data-view-type="block" data-cart="<?php echo htmlspecialchars(json_encode($arrCart), ENT_QUOTES, 'UTF-8'); ?>"> 
    <h4>Have Apple Pay?</h4> 
    <div class="field opt note"></div> 
    <div class="field text"> 
        <label class="scr-only" for="phone">Phone number</label> 
        <input class="input-text" id="phone" name="phone" type="tel"> 
    </div> 
    <div class="field opt"> 
        <input class="input-checkbox" id="save-phone-number-1" name="save-phone" type="checkbox"> 
        <label for="save-phone-number-1">Save phone number</label> 
    </div> 
    <a class="taply-apply-pay taply-btn" href="/"></a> 
</div>
<?php else : ?>
<div class="module pay-module taply-block" data-type="cart" data-cart="<?php echo htmlspecialchars(json_encode($arrCart), ENT_QUOTES, 'UTF-8'); ?>"> 
    <a class="taply-apply-pay taply-btn" href="/" style="height:40px;"></a> 
</div>
<?php endif; ?>
